[project]
name = "fusioncat"
version = "2.0.0"
description = "A toolkit for 0D analysis of fusion concepts with a self-reliant physics core."
authors = [{ name = "FusionCAT Development Team" }]
requires-python = ">=3.9"
dependencies = ["astropy", "numpy", "scipy", "matplotlib", "pytest", "numba"] 